apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deployment
  minReplicas: 4  # Número mínimo de réplicas
  maxReplicas: 8  # Número máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
