apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: xxx (Codificado en BASE64)
  MYSQL_USER: xxx (Codificado en BASE64)
  MYSQL_PASSWORD: xxx (Codificado en BASE64)
  MYSQL_DATABASE: xxx (Codificado en BASE64)
